name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/github-script@v6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: " Thank you for raising an issue! We will review it shortly. Stay tuned!"
        pr-message: " 🎉 Thank you for your contribution!  We appreciate your support in making this project better."