name: Greetings

on: 
  [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { eventName, issue, payload, repo } = context;

          if (eventName === 'issues') {
            await github.rest.issues.createComment({
              issue_number: issue.number,
              owner: repo.owner,
              repo: repo.repo,
              body: 'Thank you for raising an issue! We will review it shortly. Stay tuned!'
            });
          } else if (eventName === 'pull_request_target') {
            await github.rest.issues.createComment({
              issue_number: payload.pull_request.number,
              owner: repo.owner,
              repo: repo.repo,
              body: '🎉 Thank you for your contribution! We appreciate your support in making this project better.'
            });
          }
